export default {
  message: null,
  wishlist: [],
  loggedIn: null,
  is_favorite: Boolean,
  addresses: [],
  regions: [],
  locations: [],
  voucher: [],
  errors: [],
  notification: null,
  reviews: [],
  reviewsMeta: null,
  comments: [],
  loadn: false,
  images: [],
  showForm: false,
  user: null,
  editMode: false,
  userType: "",
};
